version: '3.8'
services:
  simple_backend:
    build: ./simple_backend
    ports:
      - "5001:5000"
  simple_frontend:
    build: ./simple_frontend
    ports:
      - "8080:80"
    depends_on:
      - simple_backend
